### ISSUE TITLE
When i use E-Shop With mongodb it refuse the connection due to -process out of memory

### ISSUE THREAD

**Issue by chiragkanjariya** [totaljs/eshop-cms#18]
C:\xampp\htdocs\eshop-master\eshop-mongodb>node debug.js
----------------------------------------------------> PID: 5452 (v3.0)
====================================================
PID          : 1872
Node.js      : v4.4.7
Total.js     : v2.0.1
====================================================
Name         : E-shop
Version      : 6.0.0
Author       : Total.js Labs
Date         : 2016-08-15 12:53:40
Mode         : debug
====================================================

http://127.0.0.1:8000/

<--- Last few GCs --->

   25200 ms: Scavenge 968.6 (1010.2) -> 968.6 (1010.2) MB, 0.1 / 0 ms (+ 2.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   25773 ms: Mark-sweep 968.6 (1010.2) -> 585.4 (623.7) MB, 573.4 / 0 ms (+ 2.0 ms in 2 steps since start of marking, biggest step 2.0 ms) [last resort gc].
   26256 ms: Mark-sweep 585.4 (623.7) -> 585.4 (623.7) MB, 482.7 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001B46DCB4639 <JS Object>
    2: /* anonymous */ [C:\xampp\htdocs\eshop-master\eshop-mongodb\models\pages.js:~397] [pc=000000DCC2F3DDDA] (this=0000015404E59F29 <a SchemaBuilderEntity with map 00000283295B7CD1>,error=000
001B46DC084B9 <an ErrorBuilder with map 00000283295AB049>,model=000001B46DC041B9 <undefined>,url=000002CC55A3A4D9 <String[1]: />,callback=000001B46DC085C9 <JS Function (SharedFunctionInfo 00000
328E5AF53...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

C:\xampp\htdocs\eshop-master\eshop-mongodb>

**Comment by molda** [comment]
@chiragkanjariya Can you please provide some more informations?
Is it fresh installation of E-shop or have you been using it for a while?
How many pages, products and orders do you have in DB?
Have you changed anything in the code?
Thanks

**Comment by chiragkanjariya** [comment]
thanks for response.
